# Specifies how site content will be accessed
# Log in and authenticate directly with GitHub account
backend:
  # Uncomment below if using GitHub for Auth and remove name: git-gateway
  # name: github
  # repo: r-angeles/r-angeles.github.io
  name: git-gateway
  branch: main # optional; defaults to main
  site_domain: r-angeles.netlify.app

site_url: https://r-angeles.github.io/

media_folder: src/static/img
public_folder: /static/img

# local_backend: true

# # Cloudinary
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: name
#     api_key: key

collections:
  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "tags", "template", "tag"]
  - label: Settings
    name: settings
    editor:
      preview: false
    files:
      - label: Navigation
        name: nav items
        file: src/_data/navigationLinks.yaml
        allow_add: true
        collapsed: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
      - label: Metadata/header settings
        name: metadata items
        file: src/_data/metadata.yaml
        allow_add: false
        collapsed: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Language", name: "text", widget: "string", pattern: ['/^[a-z]{2}$/i', "Eg. en, nz, de, ko"]}
          - label: Description
            name: desc text
            widget: string
            fields:
              - label: Author Metadata
                name: author data
                widget: list
                fields: 
                  - {label: "Author", name: "text", widget: "string"}
                  - {label: "Author URL", name: "url", widget: "string"}