# Specifies how site content will be accessed
# Log in and authenticate directly with GitHub account
backend:
  name: github
  repo: r-angeles/r-angeles.github.io # name/repo
  branch: main # optional; defaults to main
  site_domain: r-angeles.netlify.app # your-site.netlify.app

site_url: https://r-angeles.github.io/ # your-site.github.io
display_url: https://r-angeles.github.io/

media_folder: "src/static/img"
public_folder: "/static/img"

local_backend: true

# # Cloudinary
# media_library:
#   name: cloudinary
#   config:
#     cloud_name: name
#     api_key: key

collections:
  - label: "Blog" # Used in the UI
    name: "blog" # Used in routes, e.g., /admin/collections/blog
    description: >
      Blogs will be stored, written, and published here.
    folder: "src/blog" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "string" }
      - { label: "Author", name: "author", widget: "string" }
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Body", name: "body", widget: "markdown" }
      - widget: select
        label: "tags"
        name: "tags"
        multiple: true
        create: true
        options: ["Tags", "tags", "template", "tag"]
  - label: "Settings"
    name: "settings"
    format: "yaml-frontmatter"
    editor:
      preview: false
    files:
      - label: "Metadata / HTML Header"
        name: "metadata-items"
        file: "src/_data/metadata.yaml"
        allow_add: false
        collapsed: false
        fields:
          - {label: "Title", name: "title", widget: "string"}
          - {label: "URL", name: "url", widget: "string"}
          - {label: "Language", name: "language", widget: "string", pattern: ['^[a-z]{2}$', "Examples -> en, nz, de, ko"]}
          - {label: "Description (Search Engine Desc)", name: "description", widget: "string"}
      - label: "Social"
        name: "social-items"
        file: "src/_data/social.yaml"
        max: 4
        collapsed: false
        fields:
        - label: "Social media"
          name: "socialLinks"
          widget: list
          summary: "Links for social media"
          fields:
            - label: "Social media link"
              name: "link"
              widget: string
              default: "https://twitter.com/@your.name"
            - label: "Social media icon"
              name: "icon"
              widget: select
              default: "Twitter"
              options:
                - label: "Facebook"
                  value: facebook.svg
                - label: "Github"
                  value: github.svg
                - label: "Instagram"
                  value: instagram.svg
                - label: "LinkedIn"
                  value: linkedin.svg
                - label: "TikTok"
                  value: tiktok.svg
                - label: "Twitter"
                  value: twitter.svg